[package]
name = "proba_to_delete"
version = "0.1.0"
authors = ["MihaiDogaru <dogarumihai2537@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
